apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: akto-k8s-ebpf
  labels:
    app: akto-collector
spec:
  selector:
    matchLabels:
      app: akto-collector
  template:
    metadata:
      labels:
        app: akto-collector
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: mirror-api-logging
          image: public.ecr.aws/aktosecurity/mirror-api-logging:k8s_ebpf_core_imp
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 50Mi
          env:
            - name: AKTO_TRAFFIC_BATCH_TIME_SECS
              value: "10"
            - name: AKTO_TRAFFIC_BATCH_SIZE
              value: "100"
            - name: AKTO_KAFKA_BROKER_MAL
              value: "akto-mini-runtime-mini-runtime.default.svc.cluster.local:9092"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - ALL
              add:
                - BPF
                - PERFMON
                - SYS_PTRACE
          volumeMounts:
            - name: sys-kernel-btf
              mountPath: /sys/kernel/btf
              readOnly: true
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
      volumes:
        - name: sys-kernel-btf
          hostPath:
            path: /sys/kernel/btf
            type: Directory
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
