version: '2'

services:
  traffic-collector:
    image: aktosecurity/mirror-api-logging:k8s_agent
    env_file: ./docker-akto-collector.env
    mem_limit: 2500m
    restart: always
    network_mode: host
